project_id = "eaubppoyyivdhsnostxp"

[functions.generate-content]
verify_jwt = false

[functions.youtube-transcript]
verify_jwt = false

[functions.screenshot-capture]
verify_jwt = false

[functions.wp-upload]
verify_jwt = false

[functions.wp-upload-ftp]
verify_jwt = false
